### ISSUE TITLE
Additional Circuit Features

### ISSUE THREAD

**Issue by LokiChaos** [Victorious3/Integrated-Circuits#12]
These are just a few things that would be nice, maybe for a version 2.0.  I haven't looked into the internals too much to see how viable it would be to add these features on.

More wire colors - 3 colors are ok, but I could see wanting 4 or 8, which would allow for a 4-bit bus.  8 would permit 8-bit buses.  I assume colors are meant to mimic multi-layer PCBs?

Bus lines/Bundles - carry multiple signals along a single trace, like bundled cables.  Could also come in colors like wires to control connections.  The "cost" to build would be the same as as many individual traces, but would be a lot cleaner when you need to move groups of signals around. 

Named Nodes/Tunnels - Each given a name/number all instances are treated as linked.  Again, makes moving signals across a board easier.   See [Tunnels](http://www.cburch.com/logisim/docs/2.7/en/html/libs/wiring/tunnel.html)

More advanced Logic Units - These get a bit tricky as some will have more than 4 I/O pins, so the might need to take multiple "nodes" on the board (I would suggest 2x2 which would accommodate two possible connections per-side).

Full Adder w/ carry in - A, B, carry in, carry out and output.
Demuxer - Could even be a 1-bit: A, B, Control, Out
Bus-based gates - Same set of logic gates (and adder/demuxer), but support multiple channels in one component.

Decoders, Negators, Subtractor, Bit shifters (Buses only), etc. would be nice, but are a lower priority.
[Plexers](http://www.cburch.com/logisim/docs/2.7/en/html/libs/plexers/index.html)
[Arithmetic](http://www.cburch.com/logisim/docs/2.7/en/html/libs/arith/index.html)
[Flip-flops](http://www.cburch.com/logisim/docs/2.7/en/html/libs/mem/flipflops.html)
[Shift Register](http://www.cburch.com/logisim/docs/2.7/en/html/libs/mem/shiftreg.html)

**Comment by GopherAtl** [comment]
re: colors, It's a bit odd when you're used to bundled cables and such, but I've yet to run into a situation where the 3 colors weren't enough. But it *would* be nice if red and orange were more distinct when unpowered, they look so similar it can be hard to tell which is which.

IMO, the rest of the requests don't really fit. You're already building the equivalent of up to a 64x64 area of redstone into a single block, it seems a fair price that you sacrifice complexity in the process, being reduced to 2 dimensions and losing bundled cables. What you're wanting sounds more like the way RedLogic does integrated circuits, which is very different but also quite cool.

**Comment by Victorious3** [comment]
Colors being red and orange are mainly because they fit quite well with the green wires. I agree that they can be hard to distinguish, especially for colorblind which I should also consider. I think making this a config option would be sufficient.

@GopherAtl Never played with BuildCraft and it's cobble & stone tubes? Those are quite similar to the red & orange wire.

@LokiChaos Tunnels are a good idea, and I'll think about doing something alike. Bundled wire or anything like that is not possible due to internal limitations, same goes for the other more complex gates  you mentioned. The adder for example is meant to be built and not placed down as a single gate, too much integration there isn't wanted either.

Btw, I think a way to put labels on the circuit draft would be useful to give it a little bit more of a structure, and documentation as well, for the complex circuits.

**Comment by LokiChaos** [comment]
That's fine, I was just looking to put it more on par with standard digital logic simulators (eg: Logisim that I linked to).  I understand the limitations imposed by the implimenation.

It could also be argued past what can reasonably fit on a 64x64 node board is probably better handled via MFR PRC or an actual computer (either CC or OC).

**Comment by MFernflower** [comment]
D-Latches

**Comment by Victorious3** [comment]
Tunnels implemented via 67b5e74a0b22aef3af8be7389fa5618f9e6d3e19 and related, going to be in 0.9
Works slightly different from what you suggested @LokiChaos but that's the best I can do with the internal limitations.
