### ISSUE TITLE
Change red and orange wires

### ISSUE THREAD

**Issue by scj643** [Victorious3/Integrated-Circuits#157]
Changing red and orange wires to red and black would make more sense.

**Comment by Victorious3** [comment]
Its orange and red because those two colors (kinda) make sense on a PCB. White would look weird and black is impossible because you couldnt tell if its on or off.

**Comment by evg-zhabotinsky** [comment]
Well, I kind of agree.
I personally have difficulties with orange wires, at least on my laptop monitor.
It is difficult for me to differentiate between red and orange wires when they are offline.
And online orange wires are difficult to see on orange PCB.
Using blue instead of orange might solve it.

**Comment by scj643** [comment]
Add config option to change colors?

**Comment by skyem123** [comment]
that sounds like a decent compromise?

**Comment by Victorious3** [comment]
@skyem123, @scj643 Sounds okay, will do that for the next release.

**Comment by evg-zhabotinsky** [comment]
Some players might also want to change PCB color in addition to wires.
Just a thought though, it might not be as useful.
