### ISSUE TITLE
Duplication Glitch

### ISSUE THREAD

**Issue by horus9426** [Victorious3/Integrated-Circuits#162]
Placing an Integrated Circuit into a Socket in survival doesn't get rid of the IC in inventory.

**Comment by skyem123** [comment]
https://github.com/Victorious3/Integrated-Circuits/blob/master/src/main/java/moe/nightfall/vic/integratedcircuits/gate/Socket.java#L439-L450 and https://github.com/Victorious3/Integrated-Circuits/blob/master/src/main/java/moe/nightfall/vic/integratedcircuits/gate/Socket.java#L456-L476 do not have any code to remove the circuit from the inventory when right clicked, so that is where the problem seems to come from.
I will start working on fixing it when I have a computer that I can mod on.
(It also might be possible to check both the socket and the circuit / thing being placed for if they should be removed from the inventory when placed)
