### ISSUE TITLE
moveable iobits and use of outer ring of grid

### ISSUE THREAD

**Issue by moTechPlz** [Victorious3/Integrated-Circuits#34]
Feature request:

If you are able to move around and rotate the iobits of coresponding i/o sides in cicuit you would save up on alot of space used up by wires.

The outer ring of the grid is not usable. For 16*16 it is 60 / (256 / 100) = 22,6% of the placement space of the grid. If your able to use these you can make a much more complex circuits on lower tier tech.

I understand this would take alot of work and you ofcourse want to get the bugs out first and complete version 1.

**Comment by Victorious3** [comment]
Moving the bits wouldn't cause as much effort as you might think... but still, this becomes obsolete when I have tunnels. I once had the 16x circuits 18x but I changed it to actual 16x because it would look ugly on the assembler renderer when the image gets down-scaled. Just pick a bigger size if it doesn't fit on there, the only difference is a little bit of disk space. (gzip compressed, all the empty lines will be shrunken down anyways)

**Comment by moTechPlz** [comment]
Well in creativeMode chip size doesn't really matter. But in survivalMode higher tier IC's should be much more expensive. (more expensive equipment and higher production cost)

That was my assumption at least. What the chip tier was good for, not just size. Just thought you didn't come around to implement this yet. Maybe i'm wrong.
