### ISSUE TITLE
optiFine mod causes NullPointerException on worldLoad

### ISSUE THREAD

**Issue by moTechPlz** [Victorious3/Integrated-Circuits#53]
Empty world with a ic_circuit entity placed in it. Loading the world gives this error; http://pastebin.com/QVXheWbG
Having something connected like redStoneDust or projRed gives this error; http://pastebin.com/GsG8xFNh
Both errors are a bit funny because one time the world loads OK, the next time you get one of these errors.

Looks like optiFine is causing this bug, will see if there is a option in optFine to prevent this.

**Comment by moTechPlz** [comment]
I think it happens if the optiFine option [options->videoSettings->performance->chuckUpdates]  is set to > 1.

**Comment by Victorious3** [comment]
I looked at the errors, this is definitely something that should never happen, again. I don't know why Optifine likes to query stuff before it loaded from NBT. I could nullcheck all of it but I *hate* doing that as it will hide any actual exception that happens if the gate couldn't load properly for whatever reason.

**Comment by moTechPlz** [comment]
I\ve looked around on the internet and it looks like this is not the first thing optiFine breaks. I have uninstalled optiFine, also because of graphic glitches like z-fighting textures.
